version: "3.9"
services:
  db:
    image: ankane/pgvector:latest
    container_name: ardf_manager_db
    environment:
      POSTGRES_DB: ardf_manager
      POSTGRES_USER: ardf
      POSTGRES_PASSWORD: ardfpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ardf"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
