name: Validate ATDF Tools

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/examples/**'
      - 'schema/atdf_schema.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'schema/examples/**'
      - 'schema/atdf_schema.json'

jobs:
  validate-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
          
      - name: Validate tool descriptions
        run: |
          echo "Validating tool descriptions..."
          for tool in schema/examples/*.json; do
            echo "Validating $tool"
            python tools/validator.py "$tool"
          done 